name: converter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  auto_route: 7.0.0
  injectable: ^2.2.0
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  auto_route_generator: ^7.0.0
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  test: ^1.23.0
  mockito: ^5.4.2
  isar_generator: 3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - env/
