name: converter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  auto_route: ^7.8.0
  injectable: ^2.2.0
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  shared_preferences: ^2.2.1
  dartx: ^1.2.0
  retrofit: ^4.0.1
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  freezed: ^2.4.1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  test: ^1.24.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - env/
